import { CommandExecutor } from '../interfaces/CommandExecutor';
import { TripState } from '../dto/TripState';
import { TripStateChange } from '../dto/TripStateChange';
import { Command } from '../dto/Command';
import { ITripRepository } from '../repositories/TripRepository';
import { IChangeRepository } from '../repositories/ChangeRepository';
import mongoose from 'mongoose';
import { Logger } from '../utils/Logger';

const logger = Logger.create('CreateTripExecutor');

export class CreateTripExecutor implements CommandExecutor {
  constructor(private tripRepository: ITripRepository) {}

  async executeCommand(
    tripState: TripState | undefined,
    command: Command,
    changeRepository: IChangeRepository,
    version: number
  ): Promise<{ tripState: TripState; change: TripStateChange }> {
    // Extract payload data
    const tripId = command.tripId; // Use the temporary trip ID generated by the service
    const tripPlanId = String(command.payload['tripPlanId']);
    const startTime = new Date(command.payload['startTime']);
    const endTime = new Date(command.payload['endTime']);
    const createdBy = String(command.payload['createdBy']);
    const acl = command.payload['acl']
      ? (command.payload['acl'] as Array<{ userId: string; role: string }>)
      : [];

    // Create trip in database using repository with the specified trip ID
    const tripObjectId = new mongoose.Types.ObjectId(tripId);
    const trip = await this.tripRepository.createTrip(
      tripPlanId,
      startTime,
      endTime,
      createdBy,
      acl,
      tripObjectId
    );

    // Create new TripState instance since this is a new trip
    const newTripState = new TripState(
      tripId,
      tripPlanId,
      'PLANNED',
      startTime,
      endTime,
      acl
    );

    // Update command payload with actual created trip data
    command.payload['status'] = trip.status;

    logger.info(`Trip created: (ID: ${trip._id}) for trip plan ${tripPlanId}`);

    // Create change entity and save it
    const change = await this.createAndSaveChange(
      command,
      changeRepository,
      version
    );

    return { tripState: newTripState, change };
  }

  /**
   * Create and save change entity after executing business logic
   */
  private async createAndSaveChange(
    command: Command,
    changeRepository: IChangeRepository,
    version: number,
    timestamp?: Date
  ): Promise<TripStateChange> {
    // Create change event
    const changeEvent = new TripStateChange(command);
    changeEvent.setVersion(version);

    // Save change to database with optional timestamp
    const tripObjectId = new mongoose.Types.ObjectId(command.tripId);
    const savedChange = await changeRepository.saveChange(
      tripObjectId,
      changeEvent,
      timestamp
    );
    changeEvent.setChangeId(savedChange._id.toString());

    logger.debug(
      `Created change ${savedChange._id} for CREATE_TRIP (v${version})`
    );

    return changeEvent;
  }

  /**
   * Process business logic after creating trip
   */
  private processLogic(tripState: TripState, payload: Record<string, any>) {
    // Business logic for trip creation can be added here if needed
    logger.debug(`Processing CREATE_TRIP logic for trip ${tripState.tripId}`);
  }
}
